### ISSUE TITLE
Plugin Only works when logged in as a Developer

### ISSUE THREAD

**Issue by stephencurtis** [SkillBuilders/session-timeout#10]
Hi,
in Apex 5.1.4  with this Plugin in place,
any Modal windows dont function.
They only work when logged in as A developer , once logged out of the development console, the modal window appears blank.
To get the app working, deleting the plugin resolves it.

any body seen this behaviour with this plugin ?
in fact the plugin does not work at all unless logged into the developer console

**Comment by lschilde** [comment]
New version 1.4 of the plugin is available now. Can you please try if this resolves the problem? Thank you

**Comment by TysonJouglet** [comment]
This have been resolved in commit  4a62ec8 . Thanks!
