### ISSUE TITLE
apex-session-timeout.js line 324 - possibly misspelled variable name

### ISSUE THREAD

**Issue by hpysta** [SkillBuilders/session-timeout#5]
Hi SkillBuilders,

can you please check the file apex-session-timeout.js line 324 for the possibly misspelled name and correct it? In my opinion the name dat**e**Type shall be dat**a**Type.
I discovered this issue while trying to use the KeepAlive feature, I received the error
"SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"
After fixing this issue locally in the js file the error message disappeared.

Best regards,
István

**Comment by stephencurtis** [comment]
We uninstalled the plugin , and re-installed and it worked.
dont ask me why...

**Comment by TysonJouglet** [comment]
This have been resolved in 4a62ec8. Thanks!
