### ISSUE TITLE
apex-session-timeout.min.js missing

### ISSUE THREAD

**Issue by ghost** [SkillBuilders/session-timeout#6]
You forgot to include apex-session-timeout.min.js within the plugin.
Workaround: Upload the file from session-timeout-master\dist\js\apex-session-timeout.min.js manually in Apex, Shared Componentes | Plug-ins | SkillBuilders Session Timeout, into Directory "js/minified"

**Comment by lschilde** [comment]
We added this to new version 1.4 of the plugin now. Thank you for pointing this out.

**Comment by TysonJouglet** [comment]
This has been resolved in commit  4a62ec8. Thanks!
