### ISSUE TITLE
JSON-Parse Error with Apex 5.1.1 and Universal Theme 42

### ISSUE THREAD

**Issue by ghost** [SkillBuilders/session-timeout#7]
With KeepSessionAlive turned on this messages keeps popping up everytime _pingSession is called:
"Error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"
![grafik](https://user-images.githubusercontent.com/11388027/36895029-ae4da65c-1e0d-11e8-8100-20e253e2b879.png)

Somehow Apex does not recognize "dateType: 'text'" within the plugin(...)-Call in _pingSession.
(Edit: Since it gets ignored anyway, no need to change anything) Workaround: Change dateType to 'json' 
![grafik](https://user-images.githubusercontent.com/11388027/36895098-f2bd0cc4-1e0d-11e8-9a4a-2967fffcaa63.png)
and return an empty json-Object by modifying the ajax_session_timeout-PLSQL-Function in the following way: 
Add
    owa_util.mime_header('application/json', false);
    owa_util.http_header_close;
    apex_json.open_object();
    apex_json.close_all();
Before "RETURN l_result;". Not sure whether Returning l_result is still needed...
![grafik](https://user-images.githubusercontent.com/11388027/36895129-0f40c606-1e0e-11e8-889d-85640ca0adaa.png)

**Comment by ghost** [comment]
No need to change the javascript-File, since "text" gets ignored anyhow and you do not intent to return any value anyway. Just adding any json-return Value in the ajax_session_timeout-PLSQL-Function works.

**Comment by hpysta** [comment]
Hi 12345lamaun,

changing dat**e**Type to dat**a**Type will solve this issue, see here: 

https://github.com/SkillBuilders/session-timeout/issues/5

Best regards,
István

**Comment by TysonJouglet** [comment]
This has been resolved in commit  4a62ec8. Thanks!
