### ISSUE TITLE
JQuery UI 1.12.x directory structure change affects button rendering (APEX 18.x and higher only)

### ISSUE THREAD

**Issue by arinberger** [SkillBuilders/session-timeout#8]
Starting with APEX 18.1, the JQuery UI library is updated from version 1.10.4 to 1.12.1 which changes the folder structure and files that make up the library. This change breaks the call to apex_javascript.add_library specified in pl-sql-code.sql lines 77 - 81. (*EDIT* To be clear, the plugin still works, even with the broken call. It just does not find the button widget.)

Possible Solution 1- The plugin seems to work without the call to apex_javascript.add_library for the button widget script. The [APEX User Guide](https://docs.oracle.com/database/apex-18.1/HTMDB/understanding-jquery-and-jquery-ui-support.htm#HTMDB-GUID-F7F9124F-9956-4BED-8F0E-3EBA55184C17) describes a bundle loaded by default that includes the JQuery UI button widget, but IDK when it was first included.

Possible Solution 2- If removing the call to apex_javascript.add_library does not work for some reason, you could also change it to match the following:

```
apex_javascript.add_library(
      p_name      => 'button',
      p_directory => '#JQUERYUI_DIRECTORY#ui/widgets/',
      p_version   => NULL
   );
```

**Comment by michaelabuckley** [comment]
Me too.  I'm not sure the widget is even used, but I get a 404 in my logs, and an error on the JS console.

**Comment by TysonJouglet** [comment]
This referenced has been removed since it is not necessary and has been removed. You can get the updated plugin from release v1.4
